codecov:
  require_ci_to_pass: false

comment:
  layout: "diff, condensed_files"
  behavior: default
  require_changes: true

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
