# https://embarkstudios.github.io/cargo-deny/checks/index.html
[graph]
all-features = true

[advisories]
unmaintained = "workspace"
unsound = "all"

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[licenses]
confidence-threshold = 0.93
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "CC0-1.0",
    "ISC",
    "MIT",
    "MITNFA", # https://spdx.org/licenses/MITNFA.html
    "Unicode-3.0",
]
