#!/bin/sh
# Copyright (c) 2026 Hemi Labs, Inc.
# Use of this source code is governed by the MIT License,
# which can be found in the LICENSE file.

# Generates the consensus layer side of the localnet L1 for a geth + Prysm
# proof-of-stake L1 (L1_CONSENSUS=prysm): the Prysm chain config with the
# Gloas fork at the epoch that matches the Amsterdam time of the execution
# layer genesis, and the beacon genesis state with the interop validators,
# whose keystores are in keys/.  Called by genesisl2.sh once it has written
# the execution layer genesis to /shared-dir/l1genesis.json; rewrites that
# file the way prysmctl needs it (the forks before Amsterdam at the genesis
# time) and writes /shared-dir/prysm-config.yml and /shared-dir/genesis.ssz.
#
# Slots are SECONDS_PER_SLOT seconds and an epoch is 32 slots, so a fork
# epoch is 32*SECONDS_PER_SLOT seconds; L1_AMSTERDAM_OFFSET_SECONDS must be
# a multiple of that.

set -e

SHARED_DIR="${SHARED_DIR:-/shared-dir}"
SECONDS_PER_SLOT="${PRYSM_SECONDS_PER_SLOT:-3}"
SLOTS_PER_EPOCH=32
NUM_VALIDATORS=64
EPOCH_SECONDS=$((SECONDS_PER_SLOT * SLOTS_PER_EPOCH))

GENESIS_TIME=$(printf '%d' "$(jq -r '.timestamp' "$SHARED_DIR/l1genesis.json")")
AMSTERDAM_TIME=$(jq -r '.config.amsterdamTime' "$SHARED_DIR/l1genesis.json")
if [ "$AMSTERDAM_TIME" = "null" ] || [ "$AMSTERDAM_TIME" -le "$GENESIS_TIME" ]; then
	echo "generate-genesis: the l1 genesis must schedule Amsterdam after its genesis time (amsterdamTime: $AMSTERDAM_TIME, timestamp: $GENESIS_TIME)" >&2
	exit 1
fi
OFFSET=$((AMSTERDAM_TIME - GENESIS_TIME))
if [ $((OFFSET % EPOCH_SECONDS)) -ne 0 ]; then
	echo "generate-genesis: the Amsterdam time must be $OFFSET seconds after genesis, which is not a multiple of the $EPOCH_SECONDS second epoch" >&2
	exit 1
fi
GLOAS_FORK_EPOCH=$((OFFSET / EPOCH_SECONDS))

# Prysm wants the deposit contract in the execution genesis and named in
# its config; the localnet never deposits, so the contract is only there
# to exist.  The code is the mainnet deposit contract.
DEPOSIT_CONTRACT="0x4242424242424242424242424242424242424242"
jq --arg addr "$DEPOSIT_CONTRACT" --slurpfile deposit "$(dirname "$0")/deposit-contract.json" \
	'.alloc[$addr] = $deposit[0] | .config.depositContractAddress = $addr | .config.terminalTotalDifficultyPassed = true' \
	"$SHARED_DIR/l1genesis.json" > "$SHARED_DIR/l1genesis.json.tmp" && mv "$SHARED_DIR/l1genesis.json.tmp" "$SHARED_DIR/l1genesis.json"

cat > "$SHARED_DIR/prysm-config.yml" <<YML
# generated by e2e/prysm/generate-genesis.sh
CONFIG_NAME: interop
PRESET_BASE: interop
GENESIS_FORK_VERSION: 0x20000089
ALTAIR_FORK_EPOCH: 0
ALTAIR_FORK_VERSION: 0x20000090
BELLATRIX_FORK_EPOCH: 0
BELLATRIX_FORK_VERSION: 0x20000091
TERMINAL_TOTAL_DIFFICULTY: 0
CAPELLA_FORK_EPOCH: 0
CAPELLA_FORK_VERSION: 0x20000092
DENEB_FORK_EPOCH: 0
DENEB_FORK_VERSION: 0x20000093
ELECTRA_FORK_EPOCH: 0
ELECTRA_FORK_VERSION: 0x20000094
FULU_FORK_EPOCH: 0
FULU_FORK_VERSION: 0x20000095
# Gloas is the consensus layer side of Glamsterdam; it activates together
# with Amsterdam on the execution layer
GLOAS_FORK_EPOCH: $GLOAS_FORK_EPOCH
GLOAS_FORK_VERSION: 0x20000096
SECONDS_PER_SLOT: $SECONDS_PER_SLOT
SLOT_DURATION_MS: $((SECONDS_PER_SLOT * 1000))
SLOTS_PER_EPOCH: $SLOTS_PER_EPOCH
DEPOSIT_CONTRACT_ADDRESS: $DEPOSIT_CONTRACT
DEPOSIT_CHAIN_ID: 1337
DEPOSIT_NETWORK_ID: 1337
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: $NUM_VALIDATORS
YML

prysmctl testnet generate-genesis \
	--fork=fulu \
	--num-validators=$NUM_VALIDATORS \
	--genesis-time="$GENESIS_TIME" \
	--chain-config-file="$SHARED_DIR/prysm-config.yml" \
	--geth-genesis-json-in="$SHARED_DIR/l1genesis.json" \
	--geth-genesis-json-out="$SHARED_DIR/l1genesis.json" \
	--output-ssz="$SHARED_DIR/genesis.ssz"

echo "generate-genesis: genesis time $GENESIS_TIME, Gloas and Amsterdam at epoch $GLOAS_FORK_EPOCH (timestamp $AMSTERDAM_TIME)"
jq -c '.config | {amsterdamTime, osakaTime, depositContractAddress}' "$SHARED_DIR/l1genesis.json"
