# Copyright (c) 2024-2026 Hemi Labs, Inc.
# Use of this source code is governed by the MIT License,
# which can be found in the LICENSE file.

# GitHub Actions workflow to automatically label pull requests.
name: "Label"
on:
  pull_request_target:
    branches: ["main"]
    types: ["opened", "synchronize", "labeled", "unlabeled"]

jobs:
  labeler:
    name: "Pull Request"
    runs-on: "ubuntu-latest"
    permissions:
      pull-requests: write
    steps:
      - name: "Label pull requests"
        uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1

      - name: "Update changelog labels"
        uses: hemilabs/actions/changelog-labeler@e67f2b7d682accaeb026ebe393f8a161b2daa35b # v2.2.0
        with:
          changelog-path: "CHANGELOG.md"
          label-required: "changelog: required"
          label-skip: "changelog: skip"
          label-done: "changelog: done"
          required: true
