# Copyright (c) 2024 Hemi Labs, Inc.
# Use of this source code is governed by the MIT License,
# which can be found in the LICENSE file.

# GitHub Actions workflow to run e2e network tests.
name: "Localnet Test"
on:
  workflow_dispatch: # Manually triggered

concurrency:
  group: "${{ github.workflow }}-${{ github.event.number || github.ref }}"
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: "Test"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        go-version: [ "1.24.x" ]
    steps:
      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: "ghcr.io"
          username: "${{ github.repository_owner }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push legacy image cache
        uses: docker/build-push-action@v6
        with:
          context: ./e2e
          file: optimism-stack-legacy.Dockerfile
          push: true
          tags: hemilabs/localnet-optimism-stack-legacy:latest
          cache-from: type=registry,ref=hemilabs/localnet-optimism-stack-legacy:latest
          cache-to: type=inline

      - name: "Checkout repository"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: "build localnet"
        run: docker compose -f ./e2e/docker-compose.yml build

      - name: "remove dangling"
        run: docker system prune -f

      - name: "run localnet"
        run: HVM_PHASE0_TIMESTAMP=$(date --date='+120 seconds' +%s) docker compose -f ./e2e/docker-compose.yml up -d --wait-timeout 600

      - name: "remove more dangling"
        run: docker system prune -f

      - name: "get localnet stats"
        working-directory: ./e2e/monitor
        # XXX should this be a make command?
        run: go test -timeout 30m -v .
      
      - name: "dump logs"
        if: "always()"
        run: docker compose -f ./e2e/docker-compose.yml logs
