# Copyright (c) 2026 Hemi Labs, Inc.
# Use of this source code is governed by the MIT License,
# which can be found in the LICENSE file.

# GitHub Actions workflow to lint, build and test Rust.
name: "Rust"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: "rust-${{ github.workflow }}-${{ github.event.number || github.ref }}"
  cancel-in-progress: "${{ github.event_name == 'pull_request' }}"

env:
  # Enable terminal colours, disable incremental builds to avoid overhead.
  CARGO_TERM_COLOR: "always"
  CARGO_INCREMENTAL: "0"

permissions:
  contents: read

jobs:
  lint:
    name: "Lint"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: "Install toolchain"
        run: rustup toolchain install --no-self-update

      - name: "Setup Rust cache"
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

      - name: "Run rustfmt"
        run: cargo fmt --all -- --check

      - name: "Clippy" # It looks like you're writing Rust. Would you like help?
        run: cargo clippy --workspace --all-targets --locked -- -D warnings

  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: "Install toolchain"
        run: rustup toolchain install --no-self-update

      - name: "Setup Rust cache"
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          shared-key: "build-test"

      - name: "Build"
        run: cargo build --workspace --all-targets --verbose --locked

  test:
    name: "Test"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: "Install toolchain"
        run: rustup toolchain install --no-self-update

      - name: "Setup Rust cache"
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          shared-key: "build-test"

      - name: "Test"
        run: cargo test --workspace --verbose --locked

  deny:
    name: "Deny"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: "Run cargo-deny"
        uses: EmbarkStudios/cargo-deny-action@3fd3802e88374d3fe9159b834c7714ec57d6c979 # v2.0.15
